In [1]:
import tensorflow as tf

# Tensor

In Tensorflow all data is passed between operations in a computation graph, and these are passed in the form of Tensors

The contemporary meaning of Tensor can be take as multidimensional arrays

Summarizing:<br><br>
<table style="width:100%">
  <tr>
    <td><b>Dimension</b></td>
    <td><b>Physical Representation</b></td> 
    <td><b>Mathematical Object</b></td>
    <td><b>In Code</b></td>
  </tr>
  
  <tr>
    <td>Zero </td>
    <td>Point</td> 
    <td>Scalar (Single Number)</td>
    <td>[ 1 ]</td>
  </tr>

  <tr>
    <td>One</td>
    <td>Line</td> 
    <td>Vector (Series of Numbers) </td>
    <td>[ 1,2,3,4,... ]</td>
  </tr>
  
   <tr>
    <td>Two</td>
    <td>Surface</td> 
    <td>Matrix (Table of Numbers)</td>
    <td>[ [1,2,3,4,...], [1,2,3,4,...], [1,2,3,4,...],... ]</td>
  </tr>
  
   <tr>
    <td>Three</td>
    <td>Volume</td> 
    <td>Tensor (Cube of Numbers)</td>
    <td>[ [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...] ,...]... ]</td>
  </tr>
  
</table>

## Define multidimensional arrays using TensorFlow

In [5]:
Scalar = tf.constant([2]) #Like a point
Vector = tf.constant([2,3]) #Like a list
Matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]]) #Like a matrix
Tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]]) #A TENSOR

with tf.Session() as session:
    
    result = session.run(Scalar)
    print ('Scalar (1 entry):\n %s \n' % result)
    
    result = session.run(Vector)
    print ('Scalar (3 entries):\n %s \n' % result)
    
    result = session.run(Matrix)
    print ('Scalar (3x3 entries):\n %s \n' % result)
    
    result = session.run(Tensor)
    print ('Scalar (3x3x3 entries):\n %s \n' % result)
    
    

Scalar (1 entry):
 [2] 

Scalar (3 entries):
 [2 3] 

Scalar (3x3 entries):
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Scalar (3x3x3 entries):
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] 



## Operations with matrix

Sum

In [11]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[5,6],[7,8]])

op1 = tf.add(matrix1,matrix2)

with tf.Session() as session:
    
    result = session.run(op1)
    print('Sum of matrix: \n %s' %result)
    

Sum of matrix: 
 [[ 6  8]
 [10 12]]


Product

In [14]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[5,6],[7,8]])

op1 = tf.matmul(matrix1,matrix2)

with tf.Session() as session:
    
    result = session.run(op1)
    print('Product of matrix: \n %s' %result)
    

Product of matrix: 
 [[19 22]
 [43 50]]


## Variables

To be able to use variables in a computation graph it is necessary to initialize them before running the graph in a session.

To update the value of a variable, we simply run an assign operation that assings a value to the variable

In [15]:
state = tf.Variable(0)

Let's create a simple counter

In [25]:
one = tf.constant(1)

new_value = tf.add(state,one)

update = tf.assign(state,new_value)

Start a session:

    -> Initialize the variables
    
    -> Print initial value of **state**
    
    -> run the operation of updating the **state** variable and print the result after each update

In [27]:
with tf.Session() as session:
    #Initialize the variables
    tf.global_variables_initializer().run()
    
    print('Initial - State: %d' % session.run(state))
    
    for _ in range(3):
        #Run the operation of updating
        session.run(update)
        print('State: %d' % session.run(state))

Initial - State: 0
State: 1
State: 2
State: 3


## Placeholders

To feed data to a Tensorflow model from outside model, placeholders are needed

Placeholders can be seen as "holes" in the model, "holes" which you will pass the data to.

Data types:

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.|

<div style="text-align:center">[[Table Source]](https://www.tensorflow.org/versions/r0.9/resources/dims_types.html)</div>


Create a placeholder

In [28]:
a = tf.placeholder(tf.float32)

And define an operation

In [29]:
op = a*2

Now define and run the session, buy since we created a "hole" in the model to pass the data, when we initialize the session we are obligated to pass an argument with the data, otherwise we would get an error

To pass the data to the modelwe can call the session with an extra argument *feed_dict* in which we should pass a dictionary with each placeholder name followed by its respective data

In [30]:
#feed = {PlaceholderName : Values}
feed = {a:3.5}

with tf.Session() as session:
    
    result = session.run(fetches=op,feed_dict=feed)
    print('Result: %s' % result)

Result: 7.0


Since data in TensorFlow is passed in form of multidimensional arrays we can pass any kind of Tensor through the placeholders to get the answer to the simple multiplication operation

In [33]:
data = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] #2 matrix with shape (3x2)

feed = {a:data}

with tf.Session() as session:
    
    result = session.run(fetches=op,feed_dict=feed)
    print('Result: \n%s' % result)

Result: 
[[[  2.   4.   6.]
  [  8.  10.  12.]]

 [[ 14.  16.  18.]
  [ 20.  22.  24.]]]


## Operations

Operations are nodes that represent the mathematical operations over the tensors on a graph. These operations can be any kind of functions, like add and substract tensor or an activation function.

<div class="alert alert-success alertsuccess" style="margin-top: 20px">Other operations can be easily found in: https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html</div>

In [52]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.constant(dtype=tf.float32,value=[0.75])

op1 = tf.add(a,b)
op2 = tf.subtract(a,b)
sigmoid = tf.nn.sigmoid(c)

with tf.Session() as sess:
    
    result = sess.run(op1)
    print('Add: %d' %result)
    
    result = sess.run(op2)
    print('Substract: %d' %result)
    
    result = sess.run(sigmoid)
    print('Sigmoid: %f' %result)

Add: 7
Substract: 3
Sigmoid: 0.679179


### References

https://www.tensorflow.org/versions/r0.9/get_started/index.html<br />
http://jrmeyer.github.io/tutorial/2016/02/01/TensorFlow-Tutorial.html<br />
https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html<br />
https://www.tensorflow.org/versions/r0.9/resources/dims_types.html<br />
https://en.wikipedia.org/wiki/Dimension<br />
https://book.mql4.com/variables/arrays<br />
https://msdn.microsoft.com/en-us/library/windows/desktop/dn424131(v=vs.85).aspx<br />